### ISSUE TITLE
Certificates issued outside GitOps process have lifetime hardcoded to 30 days

### ISSUE THREAD

**Issue by paulschwarzenberger** [serverless-ca/terraform-aws-ca#126]
- following the [Getting Started](https://serverlessca.com/getting-started) guide results in a certificate with lifetime 30 days, even though `utils/client-cert.py` specifies 90 days.
- `requirements.txt` location specified in [Getting Started](https://serverlessca.com/getting-started) is incorrect

reported by @kurtismash

**Comment by kurtismash** [comment]
The `requirements.txt` issue was caused by a missing file within a client's implementation, not present in this repository.
