### ISSUE TITLE
Unable to import module 'create_root_ca': No module named 'cryptography'

### ISSUE THREAD

**Issue by hemicharly** [serverless-ca/terraform-aws-ca#198]
Hello,

I tried to implement the project using terraform as described in the documentation guide: [Getting started](https://serverlessca.com/getting-started)

- I am using the latest version of the module: "1.5.4"
- The python version I'm using is "3.12.4"
- The terraform version I'm using is "v1.8.3"
- My operating system is Linux Mint version 21

![image](https://github.com/user-attachments/assets/01a831c8-4b09-41ce-863d-91d9f8867a8f)

The deployment was successful on AWS. However, when executing Step Functions I am experiencing an error in the cryptography module.
`
{
  "errorMessage": "Unable to import module 'create_root_ca': No module named 'cryptography'",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "c36be39b-d8ed-4f8d-a729-7edc576781bf",
  "stackTrace": []
}
`
![image](https://github.com/user-attachments/assets/05aa7aa9-ee79-441d-be62-954e357540f1)

Has anyone experienced this same problem and could share how to resolve it?

**Comment by paulschwarzenberger** [comment]
Hi @hemicharly thanks for raising this issue. From the error it looks like the Lambda function dependencies, including the Python cryptography module, are not being installed. This should happen during the `terraform apply` stage using [this local-exec script](https://github.com/serverless-ca/terraform-aws-ca/blob/main/modules/terraform-aws-ca-lambda/scripts/lambda-build/create-package.sh) called by [this Terraform code](https://github.com/serverless-ca/terraform-aws-ca/blob/main/modules/terraform-aws-ca-lambda/main.tf).

Can you please look at the output of the `terraform apply` stage and see if there are any errors in running this script? As far as I know, this is the first time anyone has run this on Linux Mint.

**Comment by hemicharly** [comment]
Hi, @paulschwarzenberger  thanks for your response. 

I identified that this was exactly the problem. I need to configure my **local environment** so that I can run the `create-package.sh` script correctly.

**Comment by paulschwarzenberger** [comment]
That's great, thanks for letting me know, please don't hesitate to ask if you have any further queries.
