### ISSUE TITLE
getting local exec provisioner error while trying to deploy it

### ISSUE THREAD

**Issue by akhiloscar** [serverless-ca/terraform-aws-ca#254]
Getting the below error while trying to deploy the default example

╵
╷
│ Error: local-exec provisioner error
│ 
│   with module.certificate_authority.module.create_rsa_issuing_ca_lambda.null_resource.install_python_dependencies,
│   on .terraform/modules/certificate_authority/modules/terraform-aws-ca-lambda/main.tf line 13, in resource "null_resource" "install_python_dependencies":
│   13:   provisioner "local-exec" {
│ 
│ Error running command 'chmod +x
│ .terraform/modules/certificate_authority/modules/terraform-aws-ca-lambda/scripts/lambda-build/create-package.sh
│ .terraform/modules/certificate_authority/modules/terraform-aws-ca-lambda/scripts/lambda-build/create-package.sh
│ ': exit status 1. Output: Executing create_package.sh...
│ Error: local Python version does not match Lambda Python runtime
│ Local Python version: 3.8
│ Lambda Python version: 3.12
│ 
╵
╷
│ Error: local-exec provisioner error
│ 
│   with module.certificate_authority.module.rsa_issuing_ca_crl_lambda.null_resource.install_python_dependencies,
│   on .terraform/modules/certificate_authority/modules/terraform-aws-ca-lambda/main.tf line 13, in resource "null_resource" "install_python_dependencies":
│   13:   provisioner "local-exec" {
│ 
│ Error running command 'chmod +x
│ .terraform/modules/certificate_authority/modules/terraform-aws-ca-lambda/scripts/lambda-build/create-package.sh
│ .terraform/modules/certificate_authority/modules/terraform-aws-ca-lambda/scripts/lambda-build/create-package.sh
│ ': exit status 1. Output: Executing create_package.sh...
│ Error: local Python version does not match Lambda Python runtime
│ Local Python version: 3.8
│ Lambda Python version: 3.12

**Comment by akhiloscar** [comment]
@paulschwarzenberger , sure will try updating the python and try again

**Comment by paulschwarzenberger** [comment]
I'm assuming this worked, so am closing the issue - if not please let me know!
